export const TRAER_TODOS_LAS_PUBLICACIONES = "TRAER_TODOS_LAS_PUBLICACIONES";
export const TRAER_PUBLICACIONES_POR_USUARIO_ID = "TRAER_PUBLICACIONES_POR_USUARIO_ID";
export const ERROR_EN_PUBLICACIONES = "ERROR_EN_PUBLICACIONES";
export const LOADING_EN_PUBLICACIONES = "LOADING_EN_PUBLICACIONES";